import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { message, history } = body;

    const API_KEY = process.env.LUX_GEMINI_API_KEY?.trim();

    if (!API_KEY) {
      return NextResponse.json(
        { error: 'LUX_GEMINI_API_KEY is not defined in environment variables.' },
        { status: 500 }
      );
    }

    // Convert history into Gemini format, skipping empty messages.
    const formattedHistory = (history || []).map((msg: any) => ({
      role: msg.role === 'lux' ? 'model' : 'user',
      parts: [{ text: msg.content }]
    }));

    // Add current message
    formattedHistory.push({
      role: 'user',
      parts: [{ text: message }]
    });

    // The system prompt injecting the Lux Persona
    const systemInstruction = `
      You are Lux, Chris Barclay's main thinking partner and right-hand AI under DLX Studios.
      Tone: Casual, Stream-of-Consciousness. Unfiltered thinking.
      Protocol (The Lux Loop): Reflect, Distill, Move. Suggestions should be concrete Next Moves.
      Keep answers relatively short and helpful.
      CRITICAL CAPABILITY: You now have live internet access via Google Search Grounding. If the user asks for real-time information (weather, news, current events), answer directly using your search capabilities.
    `.trim();

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          system_instruction: {
            parts: [{ text: systemInstruction }]
          },
          tools: [
            { googleSearch: {} },
            { codeExecution: {} }
          ],
          contents: formattedHistory
        })
      }
    );

    const data = await response.json();

    if (!response.ok) {
      console.error("Gemini API Error:", data);
      return NextResponse.json({ error: data.error?.message || "Gemini API Failure" }, { status: response.status });
    }

    let reply = "";
    const parts = data.candidates?.[0]?.content?.parts;
    
    if (parts && Array.isArray(parts)) {
      parts.forEach((part: any) => {
        if (part.text) {
          reply += part.text + "\n";
        } else if (part.executableCode) {
          reply += "\n```" + (part.executableCode.language || "python").toLowerCase() + "\n" + part.executableCode.code + "\n```\n";
        } else if (part.codeExecutionResult) {
          reply += "\n*Execution Result:*\n```output\n" + part.codeExecutionResult.output + "\n```\n";
        }
      });
    }

    if (!reply.trim()) {
      reply = "No response generated by model.";
    }
    return NextResponse.json({ reply });
  } catch (err: any) {
    console.error("Endpoint Error:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
