import { NextResponse } from 'next/server';
import { agentRegistry } from '../../../config/agentRegistry';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { message, history, agentId = "lux" } = body;

    const API_KEY = process.env.LUX_GEMINI_API_KEY?.trim();

    if (!API_KEY) {
      return NextResponse.json(
        { error: 'LUX_GEMINI_API_KEY is not defined in environment variables.' },
        { status: 500 }
      );
    }

    const agent = agentRegistry[agentId] || agentRegistry["lux"];

    // Convert history into Gemini format, skipping empty messages.
    const formattedHistory = (history || []).map((msg: any) => ({
      role: msg.role === 'lux' ? 'model' : 'user', // "lux" role here just means "model" for backwards compat
      parts: [{ text: msg.content }]
    }));

    // Add current message
    formattedHistory.push({
      role: 'user',
      parts: [{ text: message }]
    });

    const tools = [];
    if (agent.tools.googleSearch) tools.push({ googleSearch: {} });
    if (agent.tools.codeExecution) tools.push({ codeExecution: {} });

    // Ensure we don't pass an empty tools array if tools are completely removed
    const requestPayload: any = {
      system_instruction: {
        parts: [{ text: agent.systemPrompt }]
      },
      contents: formattedHistory
    };
    
    if (tools.length > 0) {
      requestPayload.tools = tools;
    }

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestPayload)
      }
    );

    const data = await response.json();

    if (!response.ok) {
      console.error(`Gemini API Error [${agent.name}]:`, data);
      return NextResponse.json({ error: data.error?.message || "Gemini API Failure" }, { status: response.status });
    }

    let reply = "";
    const parts = data.candidates?.[0]?.content?.parts;
    
    if (parts && Array.isArray(parts)) {
      parts.forEach((part: any) => {
        if (part.text) {
          reply += part.text + "\n";
        } else if (part.executableCode) {
          reply += "\n```" + (part.executableCode.language || "python").toLowerCase() + "\n" + part.executableCode.code + "\n```\n";
        } else if (part.codeExecutionResult) {
          reply += "\n*Execution Result:*\n```output\n" + part.codeExecutionResult.output + "\n```\n";
        }
      });
    }

    if (!reply.trim()) {
      reply = "No response generated by model.";
    }
    return NextResponse.json({ reply });
  } catch (err: any) {
    console.error("Agent Endpoint Error:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
