import { NextResponse } from 'next/server';
import { agentRegistry } from '../../../config/agentRegistry';
import { db } from '../../../lib/firebaseAdmin';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { message, history: clientHistory, agentId = "lux", userId } = body;

    const API_KEY = process.env.LUX_GEMINI_API_KEY?.trim();

    if (!API_KEY) {
      return NextResponse.json(
        { error: 'LUX_GEMINI_API_KEY is not defined in environment variables.' },
        { status: 500 }
      );
    }

    const agent = agentRegistry[agentId] || agentRegistry["lux"];

    // 1. Atomically Read from The Vault (if User ID is provided)
    let persistentHistory: any[] = [];
    let docRef: any = null;

    if (db && userId) {
      docRef = db.collection('users').doc(userId).collection('agents').doc(agentId);
      const docSnap = await docRef.get();
      if (docSnap.exists) {
        persistentHistory = docSnap.data()?.messages || [];
      } else {
        // First interaction for this user/agent: start with the default greeting
        persistentHistory = [{ role: 'lux', content: agent.greeting }];
      }
    } else {
      // Fallback to client history if no DB or no User ID
      persistentHistory = clientHistory || [];
    }

    // Cap history to prevent Gemini context window overflow.
    // Keep the first message (greeting/persona anchor) + the most recent N messages.
    const MAX_HISTORY_MESSAGES = 60; // ~30 back-and-forth exchanges
    if (persistentHistory.length > MAX_HISTORY_MESSAGES) {
      const anchor = persistentHistory[0]; // Always preserve the initial greeting
      const recent = persistentHistory.slice(-(MAX_HISTORY_MESSAGES - 1));
      persistentHistory = [anchor, ...recent];
    }

    // Convert history into Gemini format, skipping empty messages.
    const formattedHistory = persistentHistory.map((msg: any) => ({
      role: msg.role === 'lux' ? 'model' : 'user', // "lux" role here just means "model" for backwards compat
      parts: [{ text: msg.content }]
    }));

    // Add current message
    formattedHistory.push({
      role: 'user',
      parts: [{ text: message }]
    });

    // Also push the new user message to the memory array we plan to save
    persistentHistory.push({ role: 'user', content: message });

    const tools = [];
    if (agent.tools.googleSearch) tools.push({ googleSearch: {} });
    if (agent.tools.codeExecution) tools.push({ codeExecution: {} });

    // Ensure we don't pass an empty tools array if tools are completely removed
    const requestPayload: any = {
      system_instruction: {
        parts: [{ text: agent.systemPrompt }]
      },
      contents: formattedHistory
    };
    
    if (tools.length > 0) {
      requestPayload.tools = tools;
    }

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestPayload)
      }
    );

    const data = await response.json();

    if (!response.ok) {
      console.error(`Gemini API Error [${agent.name}]:`, data);
      return NextResponse.json({ error: data.error?.message || "Gemini API Failure" }, { status: response.status });
    }

    let reply = "";
    const parts = data.candidates?.[0]?.content?.parts;
    
    if (parts && Array.isArray(parts)) {
      parts.forEach((part: any) => {
        if (part.text) {
          reply += part.text + "\n";
        } else if (part.executableCode) {
          reply += "\n```" + (part.executableCode.language || "python").toLowerCase() + "\n" + part.executableCode.code + "\n```\n";
        } else if (part.codeExecutionResult) {
          reply += "\n*Execution Result:*\n```output\n" + part.codeExecutionResult.output + "\n```\n";
        }
      });
    }

    if (!reply.trim()) {
      reply = "No response generated by model.";
    }

    // 2. Atomically Write back to The Vault
    persistentHistory.push({ role: 'lux', content: reply });

    if (docRef) {
      // Overwrite the document with the updated messages array
      await docRef.set({
        messages: persistentHistory,
        lastUpdated: new Date().toISOString()
      }, { merge: true });
    }

    return NextResponse.json({ reply, persistentHistory });
  } catch (err: any) {
    console.error("Agent Endpoint Error:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function DELETE(req: Request) {
  try {
    const { userId, agentId = "lux" } = await req.json();

    if (!userId) {
      return NextResponse.json({ error: 'userId is required' }, { status: 400 });
    }

    if (db) {
      const docRef = db.collection('users').doc(userId).collection('agents').doc(agentId);
      await docRef.delete();
      console.log(`Vault cleared for user ${userId}, agent ${agentId}`);
    }

    return NextResponse.json({ success: true });
  } catch (err: any) {
    console.error("Vault Clear Error:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
